spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-sorting
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.example: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
  pathsToMatch: /api/**

